### PR TITLE
remote_settings: fix TypeError when calling Object.entries

### LINKED ISSUE #1000: TypeError: undefined is not an object (evaluating 'e.searchParams.append')
# 🐞 bug report

### Affected Package
"@airbrake/browser": "^2.1.3"

### Description
Seems like after upgrading to v2.1.3 strange things appear in error notifier, so shortly error notifier producing errors by itself
Here few screenshots from airbrake panel:
image
image

Would be nice if it can be fixed as seems like it's crunching quiet a bit of quota everyday :)

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #1000
(TypeError: undefined is not an object (evaluating 'e.searchParams.append'))

Old browsers such as IE don't support `Object.entries`. Therefore, all the calls
to that property would fail... every 10 minutes :-(

`Object.entries` support:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#browser_compatibility

### CODE REVIEW

File: packages/browser/src/remote_settings.ts [hunk 1]
```diff
@@ -103,7 +107,7 @@ export class RemoteSettings {
   _pollUrl(opt: IOptions): string {
     const url = new URL(this._data.configRoute(opt.remoteConfigHost));
 
-    for (const [key, value] of Object.entries(NOTIFIER_INFO)) {
+    for (const [key, value] of this._entries(NOTIFIER_INFO)) {
       url.searchParams.append(key, value);
```
Comment (sgray) [inline packages/browser/src/remote_settings.ts:111]: I think this line might need a polyfill as well. `URL.searchParams` is not supported by IE. https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams#browser_compatibility

**Review by sgray — APPROVED** [review]

File: packages/browser/src/remote_settings.ts (hunk 1 above)
Comment (kyrylo) [reply packages/browser/src/remote_settings.ts:111]: Thanks, that's a good idea.
